# BÀI 1: LÀM QUEN VỚI PYTORCH

## Bài tập thực hành

### Bài 1. Tạo Tensor cơ bản

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [8]:
import torch
a = torch.tensor([[1, 2, 3], [4,5,6]],
dtype=torch.int32)

print (a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2. Tạo các Tensor thường dùng

Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [6]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4511, 0.4490, 0.0733, 0.6156],
        [0.8055, 0.7449, 0.3083, 0.6516],
        [0.4466, 0.3539, 0.6532, 0.1367]])
tensor([[-0.6139,  0.2017,  0.5771,  1.4146],
        [-0.7470, -2.2729,  0.0594,  0.6623],
        [-0.1823,  0.0642,  0.6033,  0.0357]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### Bài 3. Kiểm tra thông tin Tensor

Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [1]:
import torch

a = torch.zeros(2,3,4)
print("Tensor: ")
print("Shape: ", a.shape)
print("size: ", a.size())
print("Number of dimensions:", a.ndim)
print("Data type", a.dtype)
print(a)

Tensor: 
Shape:  torch.Size([2, 3, 4])
size:  torch.Size([2, 3, 4])
Number of dimensions: 3
Data type torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [13]:
f = torch.full((5,5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 4. Slicing và Indexing

Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [ ]:
import torch

a = torch.randn(3,4 ,5)
print("Original Tensor: ")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original Tensor: 
tensor([[[ 0.2483, -0.9514, -1.2692,  0.8164, -1.7195],
         [-0.0828,  0.5899, -0.9169,  0.4163, -2.5690],
         [-1.1208, -0.8152,  0.9836, -0.5281, -0.3353],
         [ 0.6997, -0.1541,  1.0768,  0.9880, -1.3074]],

        [[-0.6423,  1.0210, -0.4339,  0.8875, -0.7657],
         [ 0.4681,  1.2537, -0.9864, -1.3088, -1.9087],
         [-0.9947, -1.5520,  1.0375, -0.3355,  1.1187],
         [ 0.5924, -1.3030, -0.4810,  0.7522,  1.8266]],

        [[-0.4020,  0.1501,  0.5108, -2.0446, -0.7875],
         [ 0.1064, -0.4153, -1.9390, -0.6589, -0.4885],
         [ 0.4474, -0.6300,  0.6078, -0.6852, -0.2576],
         [ 0.5102, -0.5898,  1.4026,  1.4223,  1.2633]]])

Tensor a[1]:
tensor([[-0.6423,  1.0210, -0.4339,  0.8875, -0.7657],
        [ 0.4681,  1.2537, -0.9864, -1.3088, -1.9087],
        [-0.9947, -1.5520,  1.0375, -0.3355,  1.1187],
        [ 0.5924, -1.3030, -0.4810,  0.7522,  1.8266]])

Tensor a[1:, 2:4]:
tensor([[[-0.9947, -1.5520,  1.0375, -0.3355,  1.

### Bài 5. Reshape và Flatten

Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [1]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.7997,  0.0628, -0.1138, -1.6816],
        [ 1.2614, -0.1546, -0.5336,  0.1075],
        [-0.3693,  1.0753,  0.7644,  0.6711]])

Flatten:
tensor([ 0.7997,  0.0628, -0.1138, -1.6816,  1.2614, -0.1546, -0.5336,  0.1075,
        -0.3693,  1.0753,  0.7644,  0.6711])

Reshape to 3 x 2 x 2:
tensor([[[ 0.7997,  0.0628],
         [-0.1138, -1.6816]],

        [[ 1.2614, -0.1546],
         [-0.5336,  0.1075]],

        [[-0.3693,  1.0753],
         [ 0.7644,  0.6711]]])


In [1]:
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

# Kiểm tra số phần tử trước khi reshape
print("\nSố phần tử trước khi reshape:", a.numel())

print("\nFlatten:")
print(a.ravel())

# Reshape thành 3 x 2 x 2
b = a.reshape(3, 2, 2)

print("\nReshape to 3 x 2 x 2:")
print(b)

# Kiểm tra số phần tử sau khi reshape
print("\nSố phần tử sau khi reshape:", b.numel())

# Thử reshape thành 2 x 6
c = a.reshape(2, 6)

print("\nReshape to 2 x 6:")
print(c)

print("\nSố phần tử sau khi reshape 2 x 6:", c.numel())

Original:
tensor([[-1.0595,  0.5242,  1.5251, -0.1959],
        [-0.0971,  2.9849, -0.9296, -0.0473],
        [ 0.4419,  0.6843, -1.5715,  1.2698]])

Số phần tử trước khi reshape: 12

Flatten:
tensor([-1.0595,  0.5242,  1.5251, -0.1959, -0.0971,  2.9849, -0.9296, -0.0473,
         0.4419,  0.6843, -1.5715,  1.2698])

Reshape to 3 x 2 x 2:
tensor([[[-1.0595,  0.5242],
         [ 1.5251, -0.1959]],

        [[-0.0971,  2.9849],
         [-0.9296, -0.0473]],

        [[ 0.4419,  0.6843],
         [-1.5715,  1.2698]]])

Số phần tử sau khi reshape: 12

Reshape to 2 x 6:
tensor([[-1.0595,  0.5242,  1.5251, -0.1959, -0.0971,  2.9849],
        [-0.9296, -0.0473,  0.4419,  0.6843, -1.5715,  1.2698]])

Số phần tử sau khi reshape 2 x 6: 12


### Bài 6. Phép toán và nhân ma trận

Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [2]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.3321, -1.2923,  0.0861],
        [-0.3004, -0.0321, -1.9090]])
b:
tensor([[ 0.1031,  1.2837, -1.2530],
        [-0.3812,  1.1972,  0.8373]])

a + b:
tensor([[-0.2291, -0.0086, -1.1670],
        [-0.6816,  1.1651, -1.0717]])

a / b:
tensor([[-3.2226, -1.0067, -0.0687],
        [ 0.7881, -0.0268, -2.2800]])

a^2:
tensor([[1.1030e-01, 1.6700e+00, 7.4053e-03],
        [9.0239e-02, 1.0314e-03, 3.6442e+00]])

Matrix multiplication:
tensor([[-1.8010, -1.3484],
        [ 2.3198, -1.5222]])


### Bài 7. Các hàm thống kê trên Tensor

Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [3]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.6716,  0.6821,  0.0717,  1.0493],
        [-0.5892,  1.2222,  1.0000, -0.4088],
        [ 1.3920,  0.9548,  0.2293,  0.1263]])

Mean:
tensor([0.0438, 0.9530, 0.4337, 0.2556])

Standard deviation:
tensor([1.1684, 0.2701, 0.4967, 0.7376])

Cumulative sum:
tensor([[-0.6716,  0.6821,  0.0717,  1.0493],
        [-1.2608,  1.9043,  1.0717,  0.6406],
        [ 0.1313,  2.8591,  1.3010,  0.7669]])


### Bài 8. Autograd cơ bản

Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [4]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Bài 9. Gradient Descent tìm hệ số đa thức

Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [6]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])

N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.1980],
        [-0.4527],
        [-0.3281]], requires_grad=True)
Learned coefficients:
tensor([[1.0243],
        [2.0018],
        [2.0409]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [9]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
  y1 = A + B - 9
  y2 = C - D - 1
  y3 = A + C - 8
  y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(0.2533, requires_grad=True)
B = tensor(0.2982, requires_grad=True)
C = tensor(0.9914, requires_grad=True)
D = tensor(0.7389, requires_grad=True)


## 3. Bài tập áp dụng

Tạo Tensor X có 24 phần tử và reshape thành 4 × 6, 2 × 12 và 2 × 3 × 4

In [10]:
import torch

# Tạo Tensor X gồm 24 phần tử
X = torch.arange(24)

print("Tensor X ban đầu:")
print(X)

# Reshape thành 4 x 6
X_4x6 = X.reshape(4, 6)
print("\nX có kích thước 4 x 6:")
print(X_4x6)

# Reshape thành 2 x 12
X_2x12 = X.reshape(2, 12)
print("\nX có kích thước 2 x 12:")
print(X_2x12)

# Reshape thành 2 x 3 x 4
X_2x3x4 = X.reshape(2, 3, 4)
print("\nX có kích thước 2 x 3 x 4:")
print(X_2x3x4)

Tensor X ban đầu:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X có kích thước 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X có kích thước 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X có kích thước 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột

In [ ]:
import torch

# Tạo hai Tensor A và B kích thước 3 x 4
A = torch.tensor([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0],
    [9.0, 10.0, 11.0, 12.0]
])

B = torch.tensor([
    [2.0, 4.0, 6.0, 8.0],
    [1.0, 2.0, 3.0, 4.0],
    [2.0, 2.0, 2.0, 2.0]
])

print("A:")
print(A)

print("\nB:")
print(B)

# Cộng A và B
print("\nA + B:")
print(A + B)

# Nhân từng phần tử
print("\nA * B:")
print(A * B)

# Chia từng phần tử
print("\nA / B:")
print(A / B)

# Trung bình theo cột
print("\nTrung bình theo cột:")
print(A.mean(dim=0))
x``
# Độ lệch chuẩn theo cột
print("\nĐộ lệch chuẩn theo cột:")
print(A.std(dim=0))

A:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

B:
tensor([[2., 4., 6., 8.],
        [1., 2., 3., 4.],
        [2., 2., 2., 2.]])

A + B:
tensor([[ 3.,  6.,  9., 12.],
        [ 6.,  8., 10., 12.],
        [11., 12., 13., 14.]])

A * B:
tensor([[ 2.,  8., 18., 32.],
        [ 5., 12., 21., 32.],
        [18., 20., 22., 24.]])

A / B:
tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [5.0000, 3.0000, 2.3333, 2.0000],
        [4.5000, 5.0000, 5.5000, 6.0000]])

Trung bình theo cột:
tensor([5., 6., 7., 8.])

Độ lệch chuẩn theo cột:
tensor([4., 4., 4., 4.])


Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công

In [12]:
import torch

# Tạo x = 2 và cho phép PyTorch tính đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Hàm y = 2x^2 + 5x + 3
y = 2 * x**2 + 5 * x + 3

# Tính đạo hàm dy/dx
y.backward()

print("Giá trị y tại x = 2:", y.item())
print("dy/dx bằng Autograd:", x.grad.item())

# Kiểm tra bằng cách tính thủ công
# y = 2x^2 + 5x + 3
# => dy/dx = 4x + 5

dy_dx_manual = 4 * x.item() + 5

print("dy/dx tính thủ công:", dy_dx_manual)

Giá trị y tại x = 2: 21.0
dy/dx bằng Autograd: 13.0
dy/dx tính thủ công: 13.0


Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được

In [13]:
import torch

# Dữ liệu huấn luyện
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0, 3.0])

# y = 2x^2 - 3x + 5
y = 2 * x**2 - 3 * x + 5

# Khởi tạo các hệ số cần học
a = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
c = torch.tensor(0.0, requires_grad=True)

# Learning rate
learning_rate = 0.01

# Huấn luyện
for epoch in range(5000):

    # Công thức mô hình
    y_pred = a * x**2 + b * x + c

    # Tính sai số bình phương trung bình
    loss = torch.mean((y_pred - y)**2)

    # Tính gradient
    loss.backward()

    # Cập nhật các hệ số
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad

    # Xóa gradient cũ
    a.grad.zero_()
    b.grad.zero_()
    c.grad.zero_()

# In kết quả
print("Hệ số a:", a.item())
print("Hệ số b:", b.item())
print("Hệ số c:", c.item())

Hệ số a: 2.0000064373016357
Hệ số b: -3.0000061988830566
Hệ số c: 4.999971389770508


## Kết thúc